/*
 * DialogConnect.java
 *
 * Created on 18. avril 2000, 21:34
 */



/**
 *
 * @author  Berclaz Jérôme
 * @version
 */
public class DialogConnect extends javax.swing.JDialog {
  boolean ok = false;
  String lastName, firstName, iP;

  /** Creates new form DialogConnect */
  public DialogConnect(java.awt.Frame parent,boolean modal) {
    super (parent, modal);
    initComponents ();
    this.setSize(360, 220);
    pack ();
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the FormEditor.
   */
  private void initComponents () {//GEN-BEGIN:initComponents
    jPanel1 = new javax.swing.JPanel ();
    jLabelFirstName = new javax.swing.JLabel ();
    jLabelLastName = new javax.swing.JLabel ();
    jLabel3 = new javax.swing.JLabel ();
    jTextFieldFirstName = new javax.swing.JTextField ();
    jTextFieldLastName = new javax.swing.JTextField ();
    jTextFieldIP = new javax.swing.JTextField ();
    jButtonOk = new javax.swing.JButton ();
    jButtonCancel = new javax.swing.JButton ();
    getContentPane ().setLayout (new java.awt.GridBagLayout ());
    java.awt.GridBagConstraints gridBagConstraints1;
    setResizable (false);
    setTitle ("Connexion");
    addWindowListener (new java.awt.event.WindowAdapter () {
      public void windowClosing (java.awt.event.WindowEvent evt) {
        closeDialog (evt);
      }
    }
    );

    jPanel1.setLayout (new java.awt.GridBagLayout ());
    java.awt.GridBagConstraints gridBagConstraints2;
    jPanel1.setBorder (new javax.swing.border.TitledBorder("Paramètres de connexion"));
    jPanel1.setName ("");

      jLabelFirstName.setText ("Nom");

      gridBagConstraints2 = new java.awt.GridBagConstraints ();
      gridBagConstraints2.gridx = 0;
      gridBagConstraints2.gridy = 0;
      gridBagConstraints2.fill = java.awt.GridBagConstraints.BOTH;
      gridBagConstraints2.insets = new java.awt.Insets (14, 20, 0, 0);
      jPanel1.add (jLabelFirstName, gridBagConstraints2);

      jLabelLastName.setText ("Prénom");

      gridBagConstraints2 = new java.awt.GridBagConstraints ();
      gridBagConstraints2.gridx = 0;
      gridBagConstraints2.gridy = 2;
      gridBagConstraints2.gridwidth = 2;
      gridBagConstraints2.fill = java.awt.GridBagConstraints.BOTH;
      gridBagConstraints2.insets = new java.awt.Insets (10, 20, 0, 0);
      jPanel1.add (jLabelLastName, gridBagConstraints2);

      jLabel3.setText ("Serveur");

      gridBagConstraints2 = new java.awt.GridBagConstraints ();
      gridBagConstraints2.gridx = 0;
      gridBagConstraints2.gridy = 4;
      gridBagConstraints2.gridwidth = 3;
      gridBagConstraints2.fill = java.awt.GridBagConstraints.BOTH;
      gridBagConstraints2.insets = new java.awt.Insets (10, 21, 0, 0);
      jPanel1.add (jLabel3, gridBagConstraints2);


      gridBagConstraints2 = new java.awt.GridBagConstraints ();
      gridBagConstraints2.gridx = 3;
      gridBagConstraints2.gridy = 0;
      gridBagConstraints2.gridheight = 2;
      gridBagConstraints2.fill = java.awt.GridBagConstraints.BOTH;
      gridBagConstraints2.ipadx = 146;
      gridBagConstraints2.insets = new java.awt.Insets (11, 61, 8, 0);
      jPanel1.add (jTextFieldFirstName, gridBagConstraints2);


      gridBagConstraints2 = new java.awt.GridBagConstraints ();
      gridBagConstraints2.gridx = 3;
      gridBagConstraints2.gridy = 2;
      gridBagConstraints2.gridheight = 2;
      gridBagConstraints2.fill = java.awt.GridBagConstraints.BOTH;
      gridBagConstraints2.ipadx = 146;
      gridBagConstraints2.insets = new java.awt.Insets (9, 61, 8, 0);
      jPanel1.add (jTextFieldLastName, gridBagConstraints2);

      jTextFieldIP.setText ("localhost");

      gridBagConstraints2 = new java.awt.GridBagConstraints ();
      gridBagConstraints2.gridx = 3;
      gridBagConstraints2.gridy = 4;
      gridBagConstraints2.gridheight = 2;
      gridBagConstraints2.fill = java.awt.GridBagConstraints.BOTH;
      gridBagConstraints2.ipadx = 77;
      gridBagConstraints2.insets = new java.awt.Insets (9, 61, 8, 0);
      jPanel1.add (jTextFieldIP, gridBagConstraints2);


    gridBagConstraints1 = new java.awt.GridBagConstraints ();
    gridBagConstraints1.gridx = 0;
    gridBagConstraints1.gridy = 0;
    gridBagConstraints1.gridwidth = 3;
    gridBagConstraints1.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints1.ipadx = 28;
    gridBagConstraints1.ipady = -7;
    gridBagConstraints1.insets = new java.awt.Insets (3, 10, 3, 9);
    getContentPane ().add (jPanel1, gridBagConstraints1);

    jButtonOk.setText ("Ok");
    jButtonOk.addActionListener (new java.awt.event.ActionListener () {
      public void actionPerformed (java.awt.event.ActionEvent evt) {
        jButtonOkActionPerformed (evt);
      }
    }
    );


    gridBagConstraints1 = new java.awt.GridBagConstraints ();
    gridBagConstraints1.gridx = 0;
    gridBagConstraints1.gridy = 1;
    gridBagConstraints1.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints1.insets = new java.awt.Insets (10, 50, 10, 0);
    getContentPane ().add (jButtonOk, gridBagConstraints1);

    jButtonCancel.setText ("Annuler");
    jButtonCancel.addActionListener (new java.awt.event.ActionListener () {
      public void actionPerformed (java.awt.event.ActionEvent evt) {
        jButtonCancelActionPerformed (evt);
      }
    }
    );


    gridBagConstraints1 = new java.awt.GridBagConstraints ();
    gridBagConstraints1.gridx = 1;
    gridBagConstraints1.gridy = 1;
    gridBagConstraints1.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints1.insets = new java.awt.Insets (10, 103, 10, 0);
    getContentPane ().add (jButtonCancel, gridBagConstraints1);

  }//GEN-END:initComponents

  private void jButtonCancelActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
// Add your handling code here:
    this.dispose();
  }//GEN-LAST:event_jButtonCancelActionPerformed

  private void jButtonOkActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkActionPerformed
// Add your handling code here:
    ok = true;
    lastName = jTextFieldLastName.getText();
    firstName = jTextFieldFirstName.getText();
    iP = jTextFieldIP.getText();
    this.dispose();
  }//GEN-LAST:event_jButtonOkActionPerformed

  /** Closes the dialog */
  private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
    setVisible (false);
    dispose ();
  }//GEN-LAST:event_closeDialog



  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel jPanel1;
  private javax.swing.JLabel jLabelFirstName;
  private javax.swing.JLabel jLabelLastName;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JTextField jTextFieldFirstName;
  private javax.swing.JTextField jTextFieldLastName;
  private javax.swing.JTextField jTextFieldIP;
  private javax.swing.JButton jButtonOk;
  private javax.swing.JButton jButtonCancel;
  // End of variables declaration//GEN-END:variables

}
