/*
 * ClientFrame.java
 *
 * Created on 18. avril 2000, 16:10
 */


/**
 * @author Berclaz Jérôme
 * @version
 */

package com.leflat.jass.client;

import com.leflat.jass.common.Card;

import java.awt.event.*;
import java.util.Collections;
import java.util.List;

public class ClientFrame extends javax.swing.JFrame {
    // Variables visuelles
    CanvasBorder leftCanvas;
    CanvasBorder rightCanvas;
    CanvasPlayer playerCanvas;
    CanvasTop topCanvas;
    CanvasCenter centerCanvas;
    CanvasLastPlie lastPlieCanvas;

    // Autres variables
    FlatJassClientSystem app;

    /**
     * Creates new form ClientFrame
     */
    public ClientFrame(FlatJassClientSystem app) {
        initComponents();
        this.app = app;
        leftCanvas = new CanvasBorder();
        rightCanvas = new CanvasBorder();
        playerCanvas = new CanvasPlayer();
        topCanvas = new CanvasTop();
        centerCanvas = new CanvasCenter();
        lastPlieCanvas = new CanvasLastPlie();
        leftPanel.add(leftCanvas);
        rightPanel.add(rightCanvas);
        topPanel.add(topCanvas);
        playerPanel.add(playerCanvas);
        centerPanel.add(centerCanvas);
        lastPliePanel.add(lastPlieCanvas);
        playerCanvas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                playerCanvas_mouseClicked(e);
            }
        });
        centerCanvas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                centerCanvas_mouseClicked(e);
            }
        });

        pack();
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        rightPanel = new javax.swing.JPanel();
        leftPanel = new javax.swing.JPanel();
        playerPanel = new javax.swing.JPanel();
        topPanel = new javax.swing.JPanel();
        centerPanel = new javax.swing.JPanel();
        lastPliePanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        statusBar = new javax.swing.JLabel();
        infoBar = new javax.swing.JLabel();
        jButtonAnounce = new javax.swing.JButton();
        jButtonConnect = new javax.swing.JButton();
        getContentPane().setLayout(new AbsoluteLayout());
        setSize(660, 565);
        setResizable(false);
        setTitle("Flat Jass System");
        setFont(new java.awt.Font("SansSerif", 0, 10));
        addWindowListener(new java.awt.event.WindowAdapter() {
                              public void windowClosing(java.awt.event.WindowEvent evt) {
                                  exitForm(evt);
                              }
                          }
        );

        rightPanel.setLayout(new java.awt.GridLayout(1, 1));
        rightPanel.setName("rightPanel");


        getContentPane().add(rightPanel, new AbsoluteConstraints(510, 0, 120,
                450));

        leftPanel.setLayout(new java.awt.GridLayout(1, 1));
        leftPanel.setName("leftPanel");


        getContentPane().add(leftPanel, new AbsoluteConstraints(0, 0, 120,
                450));

        playerPanel.setLayout(new java.awt.GridLayout(1, 1));


        getContentPane().add(playerPanel, new AbsoluteConstraints(120, 330,
                390, 120));

        topPanel.setLayout(new java.awt.GridLayout(1, 1));


        getContentPane().add(topPanel, new AbsoluteConstraints(120, 0, 390,
                120));

        centerPanel.setLayout(new java.awt.GridLayout(1, 1));
        centerPanel.setBackground(new java.awt.Color(51, 102, 0));


        getContentPane().add(centerPanel, new AbsoluteConstraints(120, 120,
                390, 210));

        lastPliePanel.setLayout(new java.awt.GridLayout(1, 1));


        getContentPane().add(lastPliePanel, new AbsoluteConstraints(0, 450,
                630, 40));

        jPanel1.setBorder(new javax.swing.border.BevelBorder(1));


        jPanel1.add(statusBar);
        jPanel1.add(infoBar);


        getContentPane().add(jPanel1, new AbsoluteConstraints(0, 490, 400, 40));

        jButtonAnounce.setAlignmentY(0.4F);
        jButtonAnounce.setText("Annoncer");
        jButtonAnounce.setEnabled(false);
        jButtonAnounce.addActionListener(new java.awt.event.ActionListener() {
                                             public void actionPerformed(java.awt.event.ActionEvent evt) {
                                                 jButtonAnounceActionPerformed(evt);
                                             }
                                         }
        );


        getContentPane().add(jButtonAnounce, new AbsoluteConstraints(530, 500,
                -1, -1));

        jButtonConnect.setText("Connexion");
        jButtonConnect.addActionListener(new java.awt.event.ActionListener() {
                                             public void actionPerformed(java.awt.event.ActionEvent evt) {
                                                 jButtonConnectActionPerformed(evt);
                                             }
                                         }
        );


        getContentPane().add(jButtonConnect, new AbsoluteConstraints(410, 500,
                -1, -1));

    }//GEN-END:initComponents

    private void jButtonConnectActionPerformed(java.awt.event.ActionEvent evt) {
        //GEN-FIRST:event_jButtonConnectActionPerformed
        // Add your handling code here:
        if (jButtonConnect.getText() == "Connexion") {
            DialogConnect dc = new DialogConnect(this, true);
            dc.show();
            if (dc.ok) {      // Connexion
                if (app.connect(dc.firstName, dc.lastName, dc.iP) != -1)
                    jButtonConnect.setText("Déconnexion");
            }
        } else {
            // TODO: DISPLAY A CONFIRMATION MSG
            disconnect();
            app.disconnect();
        }
    }//GEN-LAST:event_jButtonConnectActionPerformed

    public void disconnect() {
        playerCanvas.clearHand();
        playerCanvas.setName("");
        playerCanvas.setAtout(false);
        leftCanvas.setNbrCards(0);
        leftCanvas.setMode(1);
        leftCanvas.setName("");
        leftCanvas.setAtout(false);
        rightCanvas.setNbrCards(0);
        rightCanvas.setMode(1);
        rightCanvas.setName("");
        rightCanvas.setAtout(false);
        topCanvas.setNbrCards(0);
        topCanvas.setMode(1);
        topCanvas.setName("");
        topCanvas.setAtout(false);
        centerCanvas.setMode( 0);
        centerCanvas.repaint();
        removeLastPlie();
        lastPlieCanvas.setAtout(4);
        setScore(0, 0);
        repaint(31);

        statusBar.setText("Deconnexion");
        jButtonConnect.setText("Connexion");
    }

    private void jButtonAnounceActionPerformed(java.awt.event.ActionEvent evt) {
//GEN-FIRST:event_jButtonAnounceActionPerformed
// Add your handling code here:
        app.findAnouncement();
    }//GEN-LAST:event_jButtonAnounceActionPerformed

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel rightPanel;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JPanel playerPanel;
    private javax.swing.JPanel topPanel;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JPanel lastPliePanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel statusBar;
    private javax.swing.JLabel infoBar;
    private javax.swing.JButton jButtonAnounce;
    private javax.swing.JButton jButtonConnect;
    // End of variables declaration//GEN-END:variables


    //Fait un repaint des différents canvas
    public void repaint(int nbr) {
        if ((nbr & 1) == 1)
            playerCanvas.repaint();
        if ((nbr & 2) == 2)
            leftCanvas.repaint();
        if ((nbr & 4) == 4)
            topCanvas.repaint();
        if ((nbr & 8) == 8)
            rightCanvas.repaint();
        if ((nbr & 16) == 16)
            centerCanvas.repaint();
    }

    // attribue ses cartes aux joueur
    public void setPlayerCards(List<Card> hand) {
        playerCanvas.setHand(hand);
    }

    // indique le nombre de cartes des adversaires / partenaire
    public void setOpponentCards(int player, int number) {
        int diff = player - app.getPlayerId();
        if (diff < 0)
            diff += 4;
        switch (diff) {
            case 1:
                rightCanvas.setMode(1);
                rightCanvas.setNbrCards(number);
                break;
            case 2:
                topCanvas.setMode(1);
                topCanvas.setNbrCards(number);
                break;
            case 3:
                leftCanvas.setMode(1);
                leftCanvas.setNbrCards(number);
        }
    }

    void playerCanvas_mouseClicked(MouseEvent e) {
        if (playerCanvas.getMode() == 0) {
            return;
        }
        var card = playerCanvas.getCard(e.getX(), e.getY());
        if (card == null) {
            return;
        }
        int res = app.playCard(playerCanvas.getMode(), card);
        switch (res) {
            case 0:  // jouer la carte
                jButtonAnounce.setEnabled(false);
                setStatusBar(""); // remove "a vous de..."
                centerCanvas.showCard(card, 0); //cardsChoosen[0] = playedCard;
                playerCanvas.setMode(0);
                playerCanvas.removeCard(card);
                // TODO: fix
                //app.hand[i] = 37;
                repaint(17);

                // sends the card to the server
                app.sendCard(card.getNumber(), card.getValue(app.getAtout()));
                break;
            case -1: // suivre
                System.out.println("Il faut suivre !!");
                break;
            case -2: // sous-couper
                System.out.println("Vous ne pouvez pas sous-couper!!");
                break;
        }
    }

    public void setName(int player, String name) {
        int diff = player - app.getPlayerId();
        if (diff < 0)
            diff += 4;
        switch (diff) {
            case 0:
                playerCanvas.setName(name);
                playerCanvas.repaint();
                break;
            case 1:
                rightCanvas.setName(name);
                rightCanvas.repaint();
                break;
            case 2:
                topCanvas.setName(name);
                topCanvas.repaint();
                break;
            case 3:
                leftCanvas.setName(name);
                leftCanvas.repaint();
        }
    }

    public void teamChoiceShowCard(int player, int position, int cardNumber) {
        int diff = player - app.getPlayerId();
        if (diff < 0)
            diff += 4;
        switch (diff) {
            case 0:
                playerCanvas.clearHand();
                playerCanvas.setHand(Collections.singletonList(new Card(cardNumber)));
                playerCanvas.repaint();
                break;
            case 1:
                centerCanvas.drawCard(position);
                centerCanvas.repaint();
                // TODO: fix
                //rightCanvas.setCardImage(playerCanvas.cards[cardNumber]);
                rightCanvas.setMode(0);      // tirage des équipes
                rightCanvas.repaint();
                break;
            case 2:
                centerCanvas.drawCard(position);
                centerCanvas.repaint();
                // TODO: fix
                //topCanvas.setCardImage(playerCanvas.cards[cardNumber]);
                topCanvas.setMode(0);      // tirage des équipes
                topCanvas.repaint();
                break;
            case 3:
                centerCanvas.drawCard(position);
                centerCanvas.repaint();
                // TODO: fix
                // leftCanvas.setCardImage(playerCanvas.cards[cardNumber]);
                leftCanvas.setMode(0);      // tirage des équipes
                leftCanvas.repaint();
        }
    }

    public void prepareTeamChoice() {
        centerCanvas.resetCards();
        playerCanvas.clearHand();
        leftCanvas.setNbrCards(0);
        leftCanvas.setMode(1);
        rightCanvas.setNbrCards(0);
        rightCanvas.setMode(1);
        topCanvas.setNbrCards(0);
        topCanvas.setMode(1);
        centerCanvas.setMode(1);
        centerCanvas.repaint();
        removeLastPlie();
        lastPlieCanvas.setAtout(  4);
        setScore(0, 0);
        repaint(31);
    }

    void centerCanvas_mouseClicked(MouseEvent e) {
        System.out.println("Click 1");
        int drawnCard = centerCanvas.getCard(e.getX(), e.getY());
        if (drawnCard < 0) {
            return;
        }
        centerCanvas.drawCard(drawnCard);
        centerCanvas.repaint();
        centerCanvas.setMode(1);    // on ne peut plus choisir une carte
        setStatusBar("");         // remove "veuillez tirer..."
        app.sendCard(drawnCard, 0);
    }

    // prépare l'écran pour une nouvelle partie
    void prepareMatch() {
        centerCanvas.resetCards();
        centerCanvas.setMode(3);      // mode de jeu
        lastPlieCanvas.setAtout( 4);
        lastPlieCanvas.repaint();
        repaint(31);          // repaint les 5 canvas
        setStatusBar("");
        removeLastPlie();
    }

    // affiche une carte jouée
    void showPlayedCard(int player, int number) {
        int diff = player - app.getPlayerId();
        if (diff < 0)
            diff += 4;
        centerCanvas.showCard(new Card(number), diff);
        switch (diff) {
            case 1:
                rightCanvas.removeCard();
                rightCanvas.repaint();
                break;
            case 2:
                topCanvas.removeCard();
                topCanvas.repaint();
                break;
            case 3:
                leftCanvas.removeCard();
                leftCanvas.repaint();
        }
        centerCanvas.repaint();
        // TODO: fix
        //statusBar.setText(app.players[player].getFirstName() + " a joué...");
    }

    // ramasse la plie
    void pickUpPlie(String player) {
        statusBar.setText(player + " a pris la plie");
        lastPlieCanvas.setLastPlie(centerCanvas.getShownCards());
        for (int i = 0; i < 4; i++) {
            System.out.println(i);
            // TODO: fix
            //lastPlieCanvas.cards[i] = playerCanvas.cards[centerCanvas.cardsChoosen[i]];
        }
        centerCanvas.resetCards();
        lastPlieCanvas.repaint();
        centerCanvas.repaint();
    }

    void removeLastPlie() {
        lastPlieCanvas.setLastPlie(Collections.emptyList());
        lastPlieCanvas.repaint();
    }

    void setScore(int ourScore, int theirScore) {
        lastPlieCanvas.setScore(ourScore, theirScore);
        lastPlieCanvas.repaint();
    }


    void setStatusBar(String text) {
        statusBar.setText(text);
    }

    void setAnounceEnabled(boolean b) {
        jButtonAnounce.setEnabled(b);
    }

    void setAtout(int player) {
        int diff = player - app.getPlayerId();
        if (diff < 0)
            diff += 4;

        playerCanvas.setAtout(false);
        rightCanvas.setAtout(false);
        topCanvas.setAtout(false);
        leftCanvas.setAtout(false);

        switch (diff) {
            case 0:
                playerCanvas.setAtout(true);
                break;
            case 1:
                rightCanvas.setAtout(true);
                break;
            case 2:
                topCanvas.setAtout(true);
                break;
            case 3:
                leftCanvas.setAtout(true);
        }
        repaint(31);
    }
}
