/*
 * DialogNewPart.java
 *
 * Created on 11. avril 2002, 22:17
 */

/**
 * @author Berclaz Jérôme
 * @version
 */

package com.leflat.jass.client;

public class DialogNewPart extends javax.swing.JDialog {
    private boolean newPart = false;

    /** Creates new form DialogNewPart */
    public DialogNewPart(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        pack();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jLabel1 = new javax.swing.JLabel();
        jButtonYes = new javax.swing.JButton();
        jButtonNo = new javax.swing.JButton();

        getContentPane().setLayout(new AbsoluteLayout());
        setSize(320, 180);
        setResizable(false);
        setTitle("Nouvelle partie");
        addWindowListener(new java.awt.event.WindowAdapter() {
                              public void windowClosing(java.awt.event.WindowEvent evt) {
                                  closeDialog(evt);
                              }
                          }
        );

        jLabel1.setText("Voulez vous faire une nouvelle partie?");


        getContentPane().add(jLabel1, new AbsoluteConstraints(30, 20, -1, -1));

        jButtonYes.setText("Oui");
        jButtonYes.addActionListener(new java.awt.event.ActionListener() {
                                         public void actionPerformed(java.awt.event.ActionEvent evt) {
                                             jButtonYesActionPerformed(evt);
                                         }
                                     }
        );


        getContentPane().add(jButtonYes, new AbsoluteConstraints(40, 100, -1, -1));

        jButtonNo.setText("Non");
        jButtonNo.addActionListener(new java.awt.event.ActionListener() {
                                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                            jButtonNoActionPerformed(evt);
                                        }
                                    }
        );


        getContentPane().add(jButtonNo, new AbsoluteConstraints(180, 100, -1, -1));


    }//GEN-END:initComponents

    private void jButtonNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonManualActionPerformed
// Add your handling code here:
        newPart = false;
        this.dispose();
    }//GEN-LAST:event_jButtonManualActionPerformed

    private void jButtonYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHasardActionPerformed
// Add your handling code here:
        newPart = true;
        this.dispose();
    }//GEN-LAST:event_jButtonHasardActionPerformed

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

  public boolean getNewPart() { return newPart; }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jButtonYes;
    private javax.swing.JButton jButtonNo;
    // End of variables declaration//GEN-END:variables

}
