/*
 * DialogConnect.java
 *
 * Created on 18. avril 2000, 21:34
 */

/*
 *
 * @author  Berclaz Jérôme
 * @version
 */

package com.leflat.jass.client;


import javax.swing.*;
import javax.swing.text.MaskFormatter;
import java.awt.*;
import java.text.ParseException;

public class DialogConnect extends javax.swing.JDialog {
    private static final String INITIAL_NAME = "Joueur";
    private static final String INITIAL_HOST = "ec2-18-216-29-52.us-east-2.compute.amazonaws.com";
    boolean ok = false;
    String name, host;
    int gameId;

    /**
     * Creates new form DialogConnect
     */
    public DialogConnect(java.awt.Frame parent) {
        super(parent, true);
        initComponents();
        this.setSize(360, 220);
        pack();
        jTextFieldHost.setText(INITIAL_HOST);
        jTextFieldName.setText(INITIAL_NAME);
    }

    public DialogConnect(java.awt.Frame parent, String name, String host) {
        this(parent);
        jTextFieldName.setText(name);
        jTextFieldHost.setText(host);
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanel1 = new javax.swing.JPanel();
        jLabelName = new javax.swing.JLabel();
        jLabelGame = new javax.swing.JLabel();
        jLabelServer = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        MaskFormatter formatter = null;
        try {
            formatter = new MaskFormatter("### ###");
            formatter.setValueContainsLiteralCharacters(false);
        } catch (ParseException e) {
            e.printStackTrace();
        }
        jTextFieldGame = new javax.swing.JFormattedTextField(formatter);
        jTextFieldGame.setInputVerifier(new InputVerifier() {
            @Override
            public boolean verify(JComponent jComponent) {
                var field = (JFormattedTextField) jComponent;
                String text = field.getText();
                if (text.isBlank()) {
                    return true;
                }
                return text.strip().length() == 7;
            }
        });
        jTextFieldHost = new javax.swing.JTextField();
        jButtonOk = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        getContentPane().setLayout(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints gridBagConstraints1;
        setResizable(false);
        setTitle("Connexion");
        addWindowListener(new java.awt.event.WindowAdapter() {
                              public void windowClosing(java.awt.event.WindowEvent evt) {
                                  closeDialog();
                              }
                          }
        );

        jPanel1.setLayout(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints gridBagConstraints2;
        jPanel1.setBorder(new javax.swing.border.TitledBorder("Paramètres de connexion"));

        jLabelName.setText("Nom");

        gridBagConstraints2 = new java.awt.GridBagConstraints();
        gridBagConstraints2.gridx = 0;
        gridBagConstraints2.gridy = 0;
        gridBagConstraints2.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints2.insets = new java.awt.Insets(14, 20, 0, 0);
        jPanel1.add(jLabelName, gridBagConstraints2);

        jLabelGame.setText("Jeu");

        gridBagConstraints2 = new java.awt.GridBagConstraints();
        gridBagConstraints2.gridx = 0;
        gridBagConstraints2.gridy = 2;
        gridBagConstraints2.gridwidth = 2;
        gridBagConstraints2.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints2.insets = new java.awt.Insets(10, 20, 0, 0);
        jPanel1.add(jLabelGame, gridBagConstraints2);

        jLabelServer.setText("Serveur");

        gridBagConstraints2 = new java.awt.GridBagConstraints();
        gridBagConstraints2.gridx = 0;
        gridBagConstraints2.gridy = 4;
        gridBagConstraints2.gridwidth = 3;
        gridBagConstraints2.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints2.insets = new java.awt.Insets(10, 21, 0, 0);
        jPanel1.add(jLabelServer, gridBagConstraints2);

        gridBagConstraints2 = new java.awt.GridBagConstraints();
        gridBagConstraints2.gridx = 3;
        gridBagConstraints2.gridy = 0;
        gridBagConstraints2.gridheight = 2;
        gridBagConstraints2.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints2.ipadx = 146;
        gridBagConstraints2.insets = new java.awt.Insets(11, 61, 8, 0);
        jPanel1.add(jTextFieldName, gridBagConstraints2);

        gridBagConstraints2 = new java.awt.GridBagConstraints();
        gridBagConstraints2.gridx = 3;
        gridBagConstraints2.gridy = 2;
        gridBagConstraints2.gridheight = 2;
        gridBagConstraints2.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints2.ipadx = 146;
        gridBagConstraints2.insets = new java.awt.Insets(9, 61, 8, 0);
        jPanel1.add(jTextFieldGame, gridBagConstraints2);

        gridBagConstraints2 = new java.awt.GridBagConstraints();
        gridBagConstraints2.gridx = 3;
        gridBagConstraints2.gridy = 4;
        gridBagConstraints2.gridheight = 2;
        gridBagConstraints2.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints2.ipadx = 77;
        gridBagConstraints2.insets = new java.awt.Insets(9, 61, 8, 0);
        jPanel1.add(jTextFieldHost, gridBagConstraints2);

        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 0;
        gridBagConstraints1.gridwidth = 3;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints1.ipadx = 28;
        gridBagConstraints1.ipady = -7;
        gridBagConstraints1.insets = new java.awt.Insets(3, 10, 3, 9);
        getContentPane().add(jPanel1, gridBagConstraints1);

        jButtonOk.setText("Ok");
        jButtonOk.setDefaultCapable(true);
        jButtonOk.addActionListener(this::jButtonOkActionPerformed);
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 1;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints1.insets = new java.awt.Insets(10, 50, 10, 0);
        getContentPane().add(jButtonOk, gridBagConstraints1);

        jButtonCancel.setText("Annuler");
        jButtonCancel.addActionListener(this::jButtonCancelActionPerformed);
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 1;
        gridBagConstraints1.gridy = 1;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints1.insets = new java.awt.Insets(10, 103, 10, 0);
        getContentPane().add(jButtonCancel, gridBagConstraints1);
    }//GEN-END:initComponents

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
// Add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkActionPerformed
// Add your handling code here:
        if (!jTextFieldGame.getText().isBlank() && jTextFieldGame.getValue() == null) {
            jLabelGame.setForeground(new Color(128, 0, 0));
            return;
        }
        ok = true;
        gameId = jTextFieldGame.getValue() == null ? -1 : Integer.parseInt((String) jTextFieldGame.getValue());
        name = jTextFieldName.getText();
        host = jTextFieldHost.getText();
        this.dispose();
    }//GEN-LAST:event_jButtonOkActionPerformed

    /**
     * Closes the dialog
     */
    private void closeDialog() {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelGame;
    private javax.swing.JLabel jLabelServer;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JFormattedTextField jTextFieldGame;
    private javax.swing.JTextField jTextFieldHost;
    private javax.swing.JButton jButtonOk;
    private javax.swing.JButton jButtonCancel;
    // End of variables declaration//GEN-END:variables

}
