/*
 * DialogInfo.java
 *
 * Created on 19. avril 2000, 12:05
 */



/**
 *
 * @author  Berclaz Jérôme
 * @version
 */

package com.leflat.jass.client;

import javax.swing.JLabel;

public class DialogInfo extends javax.swing.JDialog {
  JLabel[] labelLine = new javax.swing.JLabel[5];

  /** Creates new form DialogInfo */
  public DialogInfo(java.awt.Frame parent,boolean modal) {
    super (parent, modal);
    initComponents ();
    for (int i=0; i<5; i++) {
      labelLine[i] = new javax.swing.JLabel();
      getContentPane ().add (labelLine[i], new AbsoluteConstraints (20, 20 + i * 20, -1, -1));
     // labelLine[i].setLocation(20, 20 + i * 20);
    }
    pack ();
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the FormEditor.
   */
  private void initComponents () {//GEN-BEGIN:initComponents
    jButton1 = new javax.swing.JButton ();
    getContentPane ().setLayout (new AbsoluteLayout ());
    setSize(400, 200);
    setResizable (false);
    setTitle ("Information");
    addWindowListener (new java.awt.event.WindowAdapter () {
      public void windowClosing (java.awt.event.WindowEvent evt) {
        closeDialog (evt);
      }
    }
    );

    jButton1.setText ("Ok");
    jButton1.addActionListener (new java.awt.event.ActionListener () {
      public void actionPerformed (java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed (evt);
      }
    }
    );


    getContentPane ().add (jButton1, new AbsoluteConstraints (170, 140, -1, -1));

  }//GEN-END:initComponents

  private void jButton1ActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// Add your handling code here:
    dispose();
  }//GEN-LAST:event_jButton1ActionPerformed

  /** Closes the dialog */
  private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
    setVisible (false);
    dispose ();
  }//GEN-LAST:event_closeDialog


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  // End of variables declaration//GEN-END:variables

  public void setText(int line, String text) {
    labelLine[line].setText(text);
    System.out.println("Ecriture d'une ligne");
  }
}
