/*
 * DialogTeamChoice.java
 *
 * Created on 19. avril 2000, 11:37
 */



/**
 *
 * @author  Berclaz Jérôme
 * @version
 */
public class DialogTeamChoice extends javax.swing.JDialog {
  boolean hasard = true;

  /** Creates new form DialogTeamChoice */
  public DialogTeamChoice(java.awt.Frame parent,boolean modal) {
    super (parent, modal);
    initComponents ();
    pack ();
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the FormEditor.
   */
  private void initComponents () {//GEN-BEGIN:initComponents
    jLabel1 = new javax.swing.JLabel ();
    jButtonHasard = new javax.swing.JButton ();
    jButtonManual = new javax.swing.JButton ();
    jLabel2 = new javax.swing.JLabel ();
    getContentPane ().setLayout (new AbsoluteLayout ());
    setSize(330, 180);
    setResizable (false);
    setTitle ("Choix des équipes");
    addWindowListener (new java.awt.event.WindowAdapter () {
      public void windowClosing (java.awt.event.WindowEvent evt) {
        closeDialog (evt);
      }
    }
    );

    jLabel1.setText ("Voulez-vous choisir les équipes au");


    getContentPane ().add (jLabel1, new AbsoluteConstraints (30, 20, -1, -1));

    jButtonHasard.setText ("Hasard");
    jButtonHasard.addActionListener (new java.awt.event.ActionListener () {
      public void actionPerformed (java.awt.event.ActionEvent evt) {
        jButtonHasardActionPerformed (evt);
      }
    }
    );


    getContentPane ().add (jButtonHasard, new AbsoluteConstraints (40, 100, -1, -1));

    jButtonManual.setText ("Manuel");
    jButtonManual.addActionListener (new java.awt.event.ActionListener () {
      public void actionPerformed (java.awt.event.ActionEvent evt) {
        jButtonManualActionPerformed (evt);
      }
    }
    );


    getContentPane ().add (jButtonManual, new AbsoluteConstraints (180, 100, -1, -1));

    jLabel2.setText ("hasard ou manuellement ?");


    getContentPane ().add (jLabel2, new AbsoluteConstraints (60, 50, -1, -1));

  }//GEN-END:initComponents

  private void jButtonManualActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonManualActionPerformed
// Add your handling code here:
    hasard = false;
    this.dispose();
  }//GEN-LAST:event_jButtonManualActionPerformed

  private void jButtonHasardActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHasardActionPerformed
// Add your handling code here:
    this.dispose();
  }//GEN-LAST:event_jButtonHasardActionPerformed

  /** Closes the dialog */
  private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
    setVisible (false);
    dispose ();
  }//GEN-LAST:event_closeDialog



  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel jLabel1;
  private javax.swing.JButton jButtonHasard;
  private javax.swing.JButton jButtonManual;
  private javax.swing.JLabel jLabel2;
  // End of variables declaration//GEN-END:variables

}
