/*
 * ClientFrame.java
 *
 * Created on 18. avril 2000, 16:10
 */

/*
 * @author Jérôme Berclaz
 * @version 2.0
 */

package com.leflat.jass.client;

import com.leflat.jass.common.*;

import javax.swing.*;
import javax.swing.border.BevelBorder;
import java.awt.*;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Locale;

public class JassFrame extends javax.swing.JFrame implements IJassUi {
    private static final String APP_TITLE = "Jass by FLAT®";

    // Variables visuelles
    private CanvasBorder leftCanvas;
    private CanvasBorder rightCanvas;
    private CanvasPlayer playerCanvas;
    private CanvasTop topCanvas;
    private CanvasCenter centerCanvas;
    private CanvasLastPlie lastPlieCanvas;

    // Autres variables
    private IRemotePlayer myself;
    private Thread threadToSignal = null;
    private int drawnCardPosition = -1;
    private Card playedCard = null;
    private boolean announcementPressed = false;


    /**
     * Creates new form ClientFrame
     */
    public JassFrame(IRemotePlayer player) {
        this.myself = player;

        initComponents();

        leftCanvas = new CanvasBorder();
        rightCanvas = new CanvasBorder();
        playerCanvas = new CanvasPlayer();
        topCanvas = new CanvasTop();
        centerCanvas = new CanvasCenter();
        lastPlieCanvas = new CanvasLastPlie();
        leftPanel.add(leftCanvas);
        rightPanel.add(rightCanvas);
        topPanel.add(topCanvas);
        playerPanel.add(playerCanvas);
        centerPanel.add(centerCanvas);
        lastPliePanel.add(lastPlieCanvas);
        playerCanvas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                playerCanvas_mouseClicked(e);
            }
        });
        centerCanvas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                centerCanvas_mouseClicked(e);
            }
        });

        loadLogos();

        Locale locale = new Locale("fr", "CH");
        JOptionPane.setDefaultLocale(locale);

        pack();
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        rightPanel = new javax.swing.JPanel();
        leftPanel = new javax.swing.JPanel();
        playerPanel = new javax.swing.JPanel();
        topPanel = new javax.swing.JPanel();
        centerPanel = new javax.swing.JPanel();
        lastPliePanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        statusBar = new javax.swing.JLabel();
        infoBar = new javax.swing.JLabel();
        jButtonAnounce = new javax.swing.JButton();
        jButtonConnect = new javax.swing.JButton();
        getContentPane().setLayout(new AbsoluteLayout());
        setSize(660, 565);
        setResizable(false);
        setTitle(APP_TITLE);
        setFont(new java.awt.Font("SansSerif", Font.PLAIN, 10));
        addWindowListener(new java.awt.event.WindowAdapter() {
                              public void windowClosing(java.awt.event.WindowEvent evt) {
                                  exitForm(evt);
                              }
                          }
        );

        rightPanel.setLayout(new java.awt.GridLayout(1, 1));
        rightPanel.setName("rightPanel");


        getContentPane().add(rightPanel, new AbsoluteConstraints(510, 0, 120, 450));

        leftPanel.setLayout(new java.awt.GridLayout(1, 1));
        leftPanel.setName("leftPanel");


        getContentPane().add(leftPanel, new AbsoluteConstraints(0, 0, 120, 450));

        playerPanel.setLayout(new java.awt.GridLayout(1, 1));


        getContentPane().add(playerPanel, new AbsoluteConstraints(120, 330, 390, 120));

        topPanel.setLayout(new java.awt.GridLayout(1, 1));


        getContentPane().add(topPanel, new AbsoluteConstraints(120, 0, 390, 120));

        centerPanel.setLayout(new java.awt.GridLayout(1, 1));
        centerPanel.setBackground(new java.awt.Color(51, 102, 0));


        getContentPane().add(centerPanel, new AbsoluteConstraints(120, 120, 390, 210));

        lastPliePanel.setLayout(new java.awt.GridLayout(1, 1));


        getContentPane().add(lastPliePanel, new AbsoluteConstraints(0, 450, 630, 40));

        jPanel1.setBorder(new javax.swing.border.BevelBorder(BevelBorder.LOWERED));


        jPanel1.add(statusBar);
        jPanel1.add(infoBar);

        getContentPane().add(jPanel1, new AbsoluteConstraints(0, 490, 400, 40));

        jButtonAnounce.setAlignmentY(0.4F);
        jButtonAnounce.setText("Annoncer");
        jButtonAnounce.setEnabled(false);
        jButtonAnounce.addActionListener(this::jButtonAnounceActionPerformed);

        getContentPane().add(jButtonAnounce, new AbsoluteConstraints(530, 500, -1, -1));

        jButtonConnect.setText("Connexion");
        jButtonConnect.addActionListener(evt -> jButtonConnectActionPerformed());

        getContentPane().add(jButtonConnect, new AbsoluteConstraints(410, 500, -1, -1));

    }//GEN-END:initComponents

    private void jButtonConnectActionPerformed() {
        //GEN-FIRST:event_jButtonConnectActionPerformed
        if (!myself.isConnected()) {
            var dc = new DialogConnect(this, true);
            dc.setLocationRelativeTo(this);
            dc.setVisible(true);
            if (!dc.ok) {
                return;
            }
            int gameId = myself.connect(dc.name, dc.host, dc.gameId);
            if (gameId >= 0) {
                jButtonConnect.setText("Déconnexion");
                setGameId(gameId);
            } else {
                JOptionPane.showMessageDialog(null, "La connection a échoué.", "Erreur", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            int choice = JOptionPane.showConfirmDialog(this, "Voulez-vous vraiment quitter le jeu?", "Déconnexion", JOptionPane.YES_NO_OPTION);
            if (choice == 0) {
                if (myself.disconnect()) {
                    disconnect();
                }
            }
        }
    }//GEN-LAST:event_jButtonConnectActionPerformed


    private void jButtonAnounceActionPerformed(java.awt.event.ActionEvent evt) {
//GEN-FIRST:event_jButtonAnounceActionPerformed
// Add your handling code here:
        announcementPressed = true;
        setAnnouncementEnabled(false);
    }//GEN-LAST:event_jButtonAnounceActionPerformed

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel rightPanel;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JPanel playerPanel;
    private javax.swing.JPanel topPanel;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JPanel lastPliePanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel statusBar;
    private javax.swing.JLabel infoBar;
    private javax.swing.JButton jButtonAnounce;
    private javax.swing.JButton jButtonConnect;
    // End of variables declaration//GEN-END:variables


    void playerCanvas_mouseClicked(MouseEvent e) {
        playedCard = playerCanvas.getCard(e.getX(), e.getY());
        if (playedCard == null) {
            return;
        }
        playerCanvas.setMode(JassCanvas.MODE_STATIC);

        assert threadToSignal != null;
        synchronized (threadToSignal) {
            threadToSignal.notify();
        }
    }

    void centerCanvas_mouseClicked(MouseEvent e) {
        drawnCardPosition = centerCanvas.getCard(e.getX(), e.getY());
        if (drawnCardPosition < 0) {
            return;
        }
        centerCanvas.setMode(CanvasCenter.MODE_DRAW_TEAMS);    // on ne peut plus choisir une carte

        assert threadToSignal != null;
        synchronized (threadToSignal) {
            threadToSignal.notify();
        }
    }

    public void disconnect() {
        for (int i = 0; i < 4; i++) {
            var canvas = getPlayerCanvas(i);
            canvas.clearHand();
            canvas.setName("");
            canvas.setAtout(false);
            canvas.setMode(JassCanvas.MODE_STATIC);
        }
        centerCanvas.resetCards();
        centerCanvas.setMode(CanvasCenter.MODE_PASSIVE);
        clearLastPlie();
        lastPlieCanvas.hideAtout();
        setScore(0, 0);
        setGameId(-1);

        statusBar.setText("");
        jButtonConnect.setText("Connexion");
    }

    // attribue ses cartes aux joueur
    public void setPlayerHand(List<Card> hand) {
        playerCanvas.setHand(hand);
    }

    @Override
    public int chooseAtout(boolean allowedToPass) {
        DialogAtout da = new DialogAtout(this, true, allowedToPass);
        da.setLocationRelativeTo(this);
        da.setVisible(true);
        return da.getSelectedColor();
    }

    @Override
    public void setAtout(int atout, int positionOfPlayerToChooseAtout) {
        lastPlieCanvas.setAtout(atout);
        for (int i = 0; i < 4; i++) {
            var canvas = getPlayerCanvas(i);
            canvas.setAtout(i == positionOfPlayerToChooseAtout);
        }
    }

    @Override
    public void chooseCard(Thread threadToSignal) {
        this.threadToSignal = threadToSignal;
        announcementPressed = false;
        playerCanvas.setMode(JassCanvas.MODE_PLAY);
    }

    @Override
    public Card getChosenCard() {
        return playedCard;
    }

    @Override
    public void setPlayedCard(Card card, int playerPosition) {
        centerCanvas.showCard(card, playerPosition);
    }

    @Override
    public void setOtherPlayersHands(int numberOfCards) {
        var hand = new ArrayList<>(Collections.nCopies(numberOfCards, new Card(Card.BACK_NUMBER)));
        leftCanvas.setHand(hand);
        topCanvas.setHand(hand);
        rightCanvas.setHand(hand);
    }

    @Override
    public void removeCardFromPlayerHand(int playerPosition) {
        var canvas = getPlayerCanvas(playerPosition);
        canvas.removeCard();
    }

    // prépare l'écran pour une nouvelle partie
    @Override
    public void prepareGame() {
        centerCanvas.resetCards();
        centerCanvas.setMode(CanvasCenter.MODE_GAME);      // mode de jeu
        lastPlieCanvas.hideAtout();
        setStatusBar("");
        clearLastPlie();
    }

    // ramasse la plie
    @Override
    public void collectPlie(int playerPosition) {
        if (playerPosition == 0) {
            setStatusBar("Vous avez pris la plie");
        } else {
            statusBar.setText(getPlayerCanvas(playerPosition).getName() + " a pris la plie");
        }
        lastPlieCanvas.setLastPlie(centerCanvas.getShownCards());
        centerCanvas.resetCards();
    }

    void clearLastPlie() {
        lastPlieCanvas.setLastPlie(Collections.emptyList());
    }

    public void setScore(int ourScore, int opponentScore) {
        lastPlieCanvas.setScores(ourScore, opponentScore);
    }

    @Override
    public boolean hasPlayerAnnounced() {
        return announcementPressed;
    }

    @Override
    public void displayStatusMessage(String message) {
        setStatusBar(message);
    }

    @Override
    public void displayGameResult(Team winningTeam, boolean won) {
        centerCanvas.setMode(CanvasCenter.MODE_PASSIVE);
        playerCanvas.setMode(JassCanvas.MODE_STATIC);
        String message = won ? "Vous avez gagné la partie. Félicitations!" :
                "L'équipe de " + winningTeam.getPlayer(0).getName() + " & " + winningTeam.getPlayer(1).getName() + " a gagné la partie!";
        setStatusBar("Partie terminée");
        JOptionPane.showMessageDialog(this, message, "Partie terminée", JOptionPane.INFORMATION_MESSAGE);
    }

    @Override
    public boolean getNewGame() {
        int choice = JOptionPane.showConfirmDialog(this, "Voulez vous faire une nouvelle partie?", "Nouvelle partie", JOptionPane.YES_NO_OPTION);
        return choice == 0;
    }

    @Override
    public void canceledGame(int leavingPlayerPosition) {
        var canvas = getPlayerCanvas(leavingPlayerPosition);
        String message = canvas.getName() + " a quitté le jeu. La partie est interrompue.";
        setStatusBar("Partie interrompue");
        disconnect();
        JOptionPane.showMessageDialog(this, message, "Partie interrompue", JOptionPane.INFORMATION_MESSAGE);
    }

    void setStatusBar(String text) {
        statusBar.setText(text);
        statusBar.repaint();
    }

    public void setAnnouncementEnabled(boolean enable) {
        announcementPressed = false;
        jButtonAnounce.setEnabled(enable);
    }

    void setGameId(int gameId) {
        String title = gameId >= 0 ? APP_TITLE + " - Jeu " + gameId : APP_TITLE;
        setTitle(title);
    }

    @Override
    public void setPlayer(BasePlayer player, int relativePosition) {
        JassCanvas canvas = getPlayerCanvas(relativePosition);
        canvas.setName(player.getName());
        canvas.repaint();
    }

    @Override
    public void showUi(boolean enable) {
        setLocationRelativeTo(null);
        setVisible(enable);
    }

    @Override
    public TeamSelectionMethod chooseTeamSelectionMethod() {
        Object[] options = {"Hasard", "Manuel"};
        int choice = JOptionPane.showOptionDialog(this, "Comment voulez-vous choisir les équipes?", "Choix des équipes",
                JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
        return choice == 0 ? TeamSelectionMethod.RANDOM : TeamSelectionMethod.MANUAL;
    }

    @Override
    public void prepareTeamDrawing() {
        playerCanvas.clearHand();
        leftCanvas.clearHand();
        rightCanvas.clearHand();
        topCanvas.clearHand();
        centerCanvas.resetCards();
        centerCanvas.setMode(CanvasCenter.MODE_DRAW_TEAMS);
        clearLastPlie();
        lastPlieCanvas.hideAtout();
        setScore(0, 0);
    }

    @Override
    public void drawCard(Thread thread) {
        centerCanvas.setMode(CanvasCenter.MODE_PICK_CARD);
        this.threadToSignal = thread;
    }

    @Override
    public int getDrawnCardPosition() {
        return drawnCardPosition;
    }

    @Override
    public void setDrawnCard(int playerPosition, int cardPosition, Card card) {
        centerCanvas.drawCard(cardPosition);
        var canvas = getPlayerCanvas(playerPosition);
        canvas.setHand(Collections.singletonList(card));
    }

    @Override
    public BasePlayer choosePartner(List<BasePlayer> partners) {
        DialogPartnerChoice dpc = new DialogPartnerChoice(this, true);
        dpc.setLocationRelativeTo(this);
        partners.forEach(dpc::addPlayer);
        dpc.setVisible(true);
        return dpc.getSelectedPlayer();
    }

    private JassCanvas getPlayerCanvas(int relativePosition) {
        switch (relativePosition) {
            case 0:
                return playerCanvas;
            case 1:
                return rightCanvas;
            case 2:
                return topCanvas;
            case 3:
                return leftCanvas;
            default:
                throw new IndexOutOfBoundsException("Unknown canvas " + relativePosition);
        }
    }

    private void loadLogos() {
        Toolkit tk = Toolkit.getDefaultToolkit();
        List<Image> images = new ArrayList<>();

        var imagePath = getClass().getClassLoader().getResource("logos/logo_128.png");
        images.add(tk.getImage(imagePath));
        imagePath = getClass().getClassLoader().getResource("logos/logo_64.png");
        images.add(tk.getImage(imagePath));
        imagePath = getClass().getClassLoader().getResource("logos/logo_48.png");
        images.add(tk.getImage(imagePath));
        imagePath = getClass().getClassLoader().getResource("logos/logo_32.png");
        images.add(tk.getImage(imagePath));
        imagePath = getClass().getClassLoader().getResource("logos/logo_16.png");
        images.add(tk.getImage(imagePath));

        setIconImages(images);
    }
}
