import gymnasium as gym
from gymnasium import spaces
import numpy as np
from typing import Optional, Tuple, Dict, Any, List

# Import your core game logic classes
from controller import Controller
from player import Player
from strategy import RandomStrategy
from rl_agent import RLAgent
from rl.tokens import Tokens
from rl.jass_rules import Suit


class JassEnv(gym.Env):
    """
    A multi-agent (simulated) Jass environment wrapped in the Gymnasium API.
    The environment is designed to train Agent 0 against three static opponents.
    """
    metadata = {"render_modes": ["human"], "render_fps": 30}

    def __init__(self, render_mode: Optional[str] = None):
        super().__init__()

        # 1. Initialize Player and Controller components
        self.players: List[Player] = []
        for i in range(4):
            # Initially, all players use a dummy RandomStrategy
            self.players.append(Player(RandomStrategy()))

        # Set up the RLAgent (Player 0) as the learning strategy
        # NOTE: You must provide a model instance when running training!
        self.rl_model = None  # To be set externally during training setup
        self.rl_agent = RLAgent(model=None, player_ref=self.players[0])  # Initialized with placeholder
        self.players[0]._strategy = self.rl_agent
        self._controller = Controller(self.players)

        # 2. Define Observation Space (State Tokens)
        # Assuming TOKEN_LENGTH is defined in your dataset/model setup
        from dataset import TOKEN_LENGTH
        self.observation_space = spaces.Box(
            low=0, high=255, shape=(TOKEN_LENGTH,), dtype=np.int64
        )

        # 3. Define Action Space (Single output for Card or Trump)
        # Card Action (0-35) or Trump Action (36-40)
        self.action_space = spaces.Discrete(36 + 5)  # 41 total actions

        self.current_player_idx = 0
        self.render_mode = render_mode

        # Store initial scores for reward calculation
        self._initial_match_scores = [0, 0]

    def _get_obs(self) -> np.ndarray:
        """Returns the observation (token vector) for the current player."""
        player = self.players[self.current_player_idx]
        is_first_turn = self._controller._trump_suit == Suit.NONE and self._controller._trump_selection_first_turn

        # The tokens are generated by the Player instance
        return np.array(player.get_state_as_tokens(is_first_turn), dtype=np.int64)

    def reset(self, seed: Optional[int] = None, options: Optional[Dict] = None) -> Tuple[np.ndarray, Dict]:
        super().reset(seed=seed)

        # Reset game state and initial scores
        self._controller.reset()
        self.current_player_idx = self._controller._current_player
        self._initial_match_scores = list(self._controller._scores)  # Copy scores

        observation = self._get_obs()
        info = {}

        if self.render_mode == "human":
            self._render_frame()

        return observation, info

    def step(self, action: int) -> Tuple[np.ndarray, float, bool, bool, Dict]:
        # action is the single integer from the action_space (0-40)

        # 1. Check if the action is a Card Play (0-35) or Trump Choice (36-40)
        is_trump_action = action >= 36

        # 2. Execute the move for the current player (Agent 0)
        if is_trump_action:
            chosen_suit = Suit(action - 36)  # 0-3 are Suits, 4 is Pass/None
            self._controller._trump_suit = chosen_suit  # Directly set for the step

            # The Controller's play_next_turn method handles the rest of the trump logic
            # (partner choice, moving to next player, setting trump for all players)

            # We skip the explicit move execution here, as the Controller's logic is complex
            # Instead, we rely on the Controller's internal turn management to process the action
            # The Controller's logic needs to be modified to accept an action directly if running RLAgent in the loop.

            # --- CRITICAL INTEGRATION POINT ---
            # Since the Controller calls player.choose_trump_suit, we must rely on
            # the RLAgent's choose_trump_suit returning the action given here.
            # This requires a complex change to your existing Controller/RLAgent structure.
            #
            # For simplicity in this env wrapper, we will simulate the whole turn
            self._controller.play_next_turn()  # Assumes the current player is the RLAgent

        else:  # Card Action
            card_id = action
            # The Controller's play_next_turn method needs to be executed
            # Since Controller.play_next_turn already contains the logic for RLAgent
            # when controller._current_player == 0, we rely on that.
            self._controller.play_next_turn()

        # 3. Advance to the next player whose turn it is
        # Note: The Controller handles moving to the next player. We just check who it is.
        self.current_player_idx = self._controller._current_player

        # 4. Check for Termination and Calculate Reward
        terminated = self._controller._game_over
        reward = 0.0

        if terminated:
            # Reward is based on team scores at the end of the game
            our_team_score = self._controller._scores[0]
            opp_team_score = self._controller._scores[1]

            # Simple Win/Loss/Draw Reward (Standard RL setup)
            if our_team_score > opp_team_score:
                reward = 1.0
            elif our_team_score < opp_team_score:
                reward = -1.0
            else:
                reward = 0.0

        # We are using a fully-defined game (Jass), so 'truncated' is generally False.
        truncated = False

        observation = self._get_obs()
        info = {"score": self._controller._scores}

        if self.render_mode == "human":
            self._render_frame()

        return observation, reward, terminated, truncated, info

    # The remaining methods (render, close) are standard for Gymnasium, but omitted for brevity.
    def render(self):
        if self.render_mode == "rgb_array":
            return self._render_frame()

    def _render_frame(self):
        # Placeholder for game visualization (not needed for training)
        pass

    def close(self):
        pass